apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.grafana.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: grafana
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.externalPort }}
      targetPort: 3000
      protocol: TCP
      name: {{ .Values.grafana.service.name }}
  selector:
    app: grafana
