{
 "title": "Controller Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"asm-controller\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"asm-controller\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"asm-controller\"}",
     "legendFormat": "heap sys"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"asm-controller\"}",
     "legendFormat": "heap alloc"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"asm-controller\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"asm-controller\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"asm-controller\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\",container_name=~\"manager\", pod_name=~\"asm-controller-.*\"})",
     "legendFormat": "Total (kis)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container_name=~\"manager\", pod_name=~\"asm-controller-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container_name=~\"manager\", pod_name=~\"asm-controller-.*\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"asm-controller\"}[1m])",
     "legendFormat": "asm-controller (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"asm-controller\"}",
     "legendFormat": "Open FDs (asm-controller)"
    },
    {
     "expr": "container_fs_usage_bytes{job=\"kubelet\",container_name=~\"manager\", pod_name=~\"asm-controller-.*\"}",
     "legendFormat": "{{ container_name }} "
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"asm-controller\"}",
     "legendFormat": "goroutines_total"
    },
    {
     "expr": "istio_mcp_clients_total{component=\"asm-controller\"}",
     "legendFormat": "clients_total"
    },
    {
     "expr": "go_goroutines{job=\"asm-controller\"}/sum(istio_mcp_clients_total{component=\"asm-controller\"}) without (component)",
     "legendFormat": "avg_goroutines_per_client"
    }
   ]
  }
 ]
}